export function getDom() {
  return {
    pageShell: document.querySelector(".page-shell"),
    authScreen: document.querySelector("#authScreen"),
    workspace: document.querySelector(".workspace"),
    sidebarSemesterLabel: document.querySelector("#sidebarSemesterLabel"),
    sidebarSemesterRange: document.querySelector("#sidebarSemesterRange"),
    heroSemesterLabel: document.querySelector("#heroSemesterLabel"),
    heroSemesterRange: document.querySelector("#heroSemesterRange"),
    nextExamCard: document.querySelector("#nextExamCard"),
    examGrid: document.querySelector("#examGrid"),

    totalEvents: document.querySelector("#totalEvents"),
    scheduleSpan: document.querySelector("#scheduleSpan"),
    conflictCount: document.querySelector("#conflictCount"),
    courseCount: document.querySelector("#courseCount"),
    typeFilterSelect: document.querySelector("#typeFilterSelect"),
    courseFilterSelect: document.querySelector("#courseFilterSelect"),
    clearFiltersButton: document.querySelector("#clearFiltersButton"),

    composerModal: document.querySelector("#composerModal"),
    coursesModal: document.querySelector("#coursesModal"),
    editModal: document.querySelector("#editModal"),
    confirmModal: document.querySelector("#confirmModal"),
    accountModal: document.querySelector("#accountModal"),
    deleteAccountModal: document.querySelector("#deleteAccountModal"),
    sharedModalCloseElements: [...document.querySelectorAll("[data-close-modal]")],

    openComposerButton: document.querySelector("#openComposerButton"),
    closeComposerButton: document.querySelector("#closeComposerButton"),
    openCoursesButton: document.querySelector("#openCoursesButton"),
    closeCoursesButton: document.querySelector("#closeCoursesButton"),
    closeEditButton: document.querySelector("#closeEditButton"),
    closeAccountButton: document.querySelector("#closeAccountButton"),
    clearDataButton: document.querySelector("#clearDataButton"),
    openDeleteAccountButton: document.querySelector("#openDeleteAccountButton"),
    accountButton: document.querySelector("#accountButton"),
    accountName: document.querySelector("#accountName"),
    accountHint: document.querySelector("#accountHint"),
    accountDisplayName: document.querySelector("#accountDisplayName"),
    accountSettingsForm: document.querySelector("#accountSettingsForm"),
    semesterInput: document.querySelector("#semesterInput"),
    semesterStartDateInput: document.querySelector("#semesterStartDateInput"),
    semesterEndDateInput: document.querySelector("#semesterEndDateInput"),
    saveAccountSettingsButton: document.querySelector("#saveAccountSettingsButton"),
    accountSettingsMessage: document.querySelector("#accountSettingsMessage"),
    deleteAccountConfirmInput: document.querySelector("#deleteAccountConfirmInput"),
    deleteAccountMessage: document.querySelector("#deleteAccountMessage"),
    deleteAccountCancelButton: document.querySelector("#deleteAccountCancelButton"),
    deleteAccountConfirmButton: document.querySelector("#deleteAccountConfirmButton"),

    eventForm: document.querySelector("#eventForm"),
    eventTypeInputs: [...document.querySelectorAll('input[name="type"]')],
    eventNameInput: document.querySelector("#eventName"),
    eventCourseSelect: document.querySelector("#eventCourseSelect"),
    eventDateInput: document.querySelector("#eventDate"),
    eventUseCourseTimingInput: document.querySelector("#eventUseCourseTiming"),
    eventTimingPresetLabel: document.querySelector("#eventTimingPresetLabel"),
    eventStartTimeInput: document.querySelector("#eventStartTime"),
    eventEndTimeInput: document.querySelector("#eventEndTime"),
    eventDueTimeInput: document.querySelector("#eventDueTime"),
    eventNotesInput: document.querySelector("#eventNotes"),
    examTimeGroup: document.querySelector("#examTimeGroup"),
    deadlineTimeField: document.querySelector("#deadlineTimeField"),
    submitButton: document.querySelector("#submitButton"),
    formMessage: document.querySelector("#formMessage"),

    editEventForm: document.querySelector("#editEventForm"),
    editEventTypeInputs: [...document.querySelectorAll('input[name="edit_type"]')],
    editEventNameInput: document.querySelector("#editEventName"),
    editEventCourseSelect: document.querySelector("#editEventCourseSelect"),
    editEventDateInput: document.querySelector("#editEventDate"),
    editEventUseCourseTimingInput: document.querySelector("#editEventUseCourseTiming"),
    editTimingPresetLabel: document.querySelector("#editTimingPresetLabel"),
    editEventStartTimeInput: document.querySelector("#editEventStartTime"),
    editEventEndTimeInput: document.querySelector("#editEventEndTime"),
    editEventDueTimeInput: document.querySelector("#editEventDueTime"),
    editEventNotesInput: document.querySelector("#editEventNotes"),
    editExamTimeGroup: document.querySelector("#editExamTimeGroup"),
    editDeadlineTimeField: document.querySelector("#editDeadlineTimeField"),
    editSubmitButton: document.querySelector("#editSubmitButton"),
    editFormMessage: document.querySelector("#editFormMessage"),

    courseForm: document.querySelector("#courseForm"),
    courseNameInput: document.querySelector("#courseNameInput"),
    courseDayInputs: [...document.querySelectorAll('input[name="course_day"]')],
    courseStartTimeInput: document.querySelector("#courseStartTimeInput"),
    courseEndTimeInput: document.querySelector("#courseEndTimeInput"),
    courseSubmitButton: document.querySelector("#courseSubmitButton"),
    cancelCourseEditButton: document.querySelector("#cancelCourseEditButton"),
    courseMessage: document.querySelector("#courseMessage"),
    courseList: document.querySelector("#courseList"),

    confirmTitle: document.querySelector("#confirmTitle"),
    confirmBody: document.querySelector("#confirmBody"),
    confirmCancelButton: document.querySelector("#confirmCancelButton"),
    confirmApproveButton: document.querySelector("#confirmApproveButton"),
  };
}
